<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HP-15s-fq2535TU" name="TestRunner.TestRunner" tests="2" failures="1" timestamp="2021-06-14T00:42:56 IST" time="148.774" errors="0">
  <testcase name="runScenario" time="51.701" classname="TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinitions.MakeMyTripStepDefinition.validating_of(MakeMyTripStepDefinition.java:256)
at âœ½.Validating "10-7-2021", returndate of "oneway"(file:///C:/Users/USER/Downloads/hrcassignment4/src/test/java/Features/MakeMyTrip.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="97.073" classname="TestRunner.TestRunner"/>
  <system-out/>
</testsuite> <!-- TestRunner.TestRunner -->
